### PR TITLE
Support Android 9.0 Pie BiometricPrompt

### LINKED ISSUE #43: Also Use USE_BIOMETRIC Permission
Can you transform the library to **also** utilize **androidx.biometric:biometric**?

### PR DESCRIPTION
**Pull request by benwicks**
Closes #43

This PR adds another module for API 28 and above to use the system `BiometricPrompt` classes which supersede the `FingerprintManager` APIs.

### CODE REVIEW

**Comment by ajalt** [comment]
What devices are you seeing that crash on? Also, can you post the full stack trace?

**Comment by benwicks** [comment]
Sorry, that stacktrace is misleading. The next call in the trace was from our application, so we weren't using Reprint correctly, we were calling into Spass directly and not handling any exceptions. Simply changing our app's code from `return new SpassFingerprint(context).hasRegisteredFinger();` to `return Reprint.hasFingerprintRegistered();` should prevent the crash we were seeing. It was happening exclusively on Android 9 Samsung devices (Galaxy Note9, Galaxy S9+, and Galaxy S9).

I think this PR's change is still something to consider though since Reprint uses methods that are now deprecated in API 28.

I'll remove the stack trace and update the PR description since this PR doesn't necessarily fix any crashes.

**Comment by ajalt** [comment]
Ok, I've had a change to review the PR, and your code looks good. Thanks for contributing! The only comment I have is the the new constants you defined should match `BiometricConstants`, rather than `FingerprintManager`.

The `hasFingerprintRegistered` hack is really unfortunate. It boggle the mind that that function isn't supported. Especially since `BiometricPrompt` [is just a wrapper around FingerprintManager](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/biometrics/BiometricPrompt.java#211), and even [calls `FingerprintManager.hasEnrolledFingerprints` internally](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/biometrics/BiometricPrompt.java#480). The workaround you added is clever, but given how many errors caused by exotic devices Reprint has to work around already, there's a good probability that it will introduce more hard to reproduce bugs.

Have Google announced that `FingerprintManager` is going to be removed in a future version of android? If not, I'm inclined to keep using it. I don't think there's any problem with using a deprecated API internally, especially since that's exactly what `BiometricPrompt` is doing anyway.

**Comment by benwicks** [comment]
Thanks for the feedback. I don't know of any announcement regarding when `FingerprintManager` will be removed. I can close this PR for now and move the discussion back to the issue.

**Pull request closed without merging**
