### PR TITLE
Migrate to androidx

### PR DESCRIPTION
**Pull request by benwicks**
This also required compiling against API 28, updating to AGP 3.2.0, ButterKnife 9.0.0-SNAPSHOT, and the latest pass library (v1.2.6).

### CODE REVIEW

**Comment by ajalt** [comment]
I confirmed that the crashing bug is still present in Spass v1.2.6.

So there's two options that I can see at this point: merge this PR as-is and warn people in the README about the crash, or remove the spass module entirely and tell people to use Reprint 3.2.1 with the old support libraries if they need to support pre-marshmallow Samsung devices.

Neither option is ideal, so I'd like to get some feedback on what people would prefer.

**Comment by benwicks** [comment]
Do you know if Samsung is aware of the bug in their library?

**Comment by ajalt** [comment]
I don't know, but I doubt they care. The Spass SDK has always been very buggy, and reprint contains a large number of workarounds for the bugs I've found. Given that the sdk is deprecated, I don't think any more bugs will be ever fixed. If this is blocking you from being able to upgrade your projects to androix, then I think it's fine to merge with a warning in the readme about the spass module.

**Comment by benwicks** [comment]
Ok, if you are good with that. Do you want help on the readme warning?

**Comment by ajalt** [comment]
Nope, I'll go ahead and add it. Thanks!

**Pull request merged**
