### PR TITLE
Exclude support library

### PR DESCRIPTION
**Pull request by hatpick**

### CODE REVIEW

**Comment by ajalt** [comment]
Can you give me a little more information on what you mean? The support library is required to allows this library to be used on pre-Marshmallow devices.

**Comment by hatpick** [comment]
If someone has already included support library, they shouldn't re-import that when they want to use reprint, so they exclude it.

**Comment by ajalt** [comment]
Did you have conflicts? Gradle takes transitive dependencies into account, so only one version of a dependency gets used. Lots of Android libraries depend on the support libraries.

**Comment by hatpick** [comment]
Yes I was getting errors, other libraries also mention that you may wanna exclude support library if you already have it.

**Comment by ajalt** [comment]
I think that transitive dependencies are common enough that I'd rather not add these instructions. If more people run into the same problem, I'll reconsider. Thanks for the pull request!

**Pull request closed without merging**
